{{- if and .Values.createNamespace .Values.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace | quote }}
  labels:
{{ include "namespace-janitor.labels" . | indent 4 }}
{{- end }}
