{{- if .Values.alertSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.alertSecret.name | default (printf "%s-alerts" (include "namespace-janitor.fullname" .)) }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "namespace-janitor.labels" . | indent 4 }}
  {{- if .Values.alertSecret.annotations }}
  annotations:
{{ toYaml .Values.alertSecret.annotations | indent 4 }}
  {{- end }}
type: Opaque
stringData:
{{- range $key, $val := .Values.alertSecret.data }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}
