{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "namespace-janitor.serviceAccountName" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
{{ include "namespace-janitor.labels" . | indent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}
